/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FeatureBox {
  'title' : string,
  'description' : string,
  'targetRoute' : string,
  'buttonLabel' : string,
}
export interface Inquiry {
  'id' : bigint,
  'subject' : string,
  'company' : [] | [string],
  'message' : string,
  'timestamp' : Time,
  'senderName' : string,
  'senderEmail' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bootstrapAdmin' : ActorMethod<[], undefined>,
  'createInquiry' : ActorMethod<
    [string, string, string, string, [] | [string]],
    undefined
  >,
  'deleteFeatureBox' : ActorMethod<[bigint], undefined>,
  'deleteInquiry' : ActorMethod<[bigint], undefined>,
  'filterInquiriesBySubject' : ActorMethod<[string], Array<Inquiry>>,
  'getAllFeatureBoxes' : ActorMethod<[], Array<FeatureBox>>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantAdminRole' : ActorMethod<[Principal], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAdmins' : ActorMethod<[], Array<Principal>>,
  'revokeAdminRole' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveFeatureBox' : ActorMethod<[[] | [bigint], FeatureBox], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];