/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'company' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'timestamp' : Time,
  'senderName' : IDL.Text,
  'senderEmail' : IDL.Text,
});
export const FeatureBox = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'targetRoute' : IDL.Text,
  'buttonLabel' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bootstrapAdmin' : IDL.Func([], [], []),
  'createInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'deleteFeatureBox' : IDL.Func([IDL.Nat], [], []),
  'deleteInquiry' : IDL.Func([IDL.Nat], [], []),
  'filterInquiriesBySubject' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Inquiry)],
      ['query'],
    ),
  'getAllFeatureBoxes' : IDL.Func([], [IDL.Vec(FeatureBox)], ['query']),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'grantAdminRole' : IDL.Func([IDL.Principal], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'revokeAdminRole' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveFeatureBox' : IDL.Func([IDL.Opt(IDL.Nat), FeatureBox], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'company' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'timestamp' : Time,
    'senderName' : IDL.Text,
    'senderEmail' : IDL.Text,
  });
  const FeatureBox = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'targetRoute' : IDL.Text,
    'buttonLabel' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bootstrapAdmin' : IDL.Func([], [], []),
    'createInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'deleteFeatureBox' : IDL.Func([IDL.Nat], [], []),
    'deleteInquiry' : IDL.Func([IDL.Nat], [], []),
    'filterInquiriesBySubject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Inquiry)],
        ['query'],
      ),
    'getAllFeatureBoxes' : IDL.Func([], [IDL.Vec(FeatureBox)], ['query']),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'grantAdminRole' : IDL.Func([IDL.Principal], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'revokeAdminRole' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveFeatureBox' : IDL.Func([IDL.Opt(IDL.Nat), FeatureBox], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };